spring.application.name=suministros
# Configuración de la Base de Datos (MariaDB)
spring.datasource.url=jdbc:mariadb://localhost:3307/clinica_santamaria
spring.datasource.username=santamaria_user
spring.datasource.password=user_secure_pass
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# Estrategia de Hibernate (Generación automática de tablas basadas en entidades)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Puerto por defecto del backend
server.address=0.0.0.0
server.port=8082